### ISSUE TITLE
Why not wiki-links?

### ISSUE THREAD

**Issue by srid** [artempyanykh/zeta-note#1]
Any reason for choosing `[:another-note]` over the more widely used `[[another-note]]` syntax? Maybe I'm missing the trade-offs behind this decision, but using wiki-links means your notebook works with a wide variety of editors and tools.

**Comment by artempyanykh** [comment]
Hey @srid :wave: Nice to meet the author of neuron!

TBH `[:note]` vs `[[note]]` was chosen because of behaviour of the parser, e.g. `some text [[note]] other text` was parsed as `TextNode("some text [")` + `LinkNode(text="note")` + `TextNode("] other text")`, which is valid according to CommonMark, but complicated things a bit wrt. symbol highlighting, completion, etc. 

At the moment I didn't want to spend much time on this, so chose `[:note]` syntax to have progress because it always parses as `LinkNode(text=":note")` and is highlighted just fine using standard editor's MD syntax highlighting.

I'm totally fine with supporting `[[...]]` syntax, it just requires a bit more work around parsing.

**Comment by srid** [comment]
Ah, I see. I see that you are using `pulldown-cmark` which doesn't give an AST, but `comrak` does: https://crates.io/crates/comrak#related-projects

Anyway I was just curious, as I wanted to try this project's LSP support in VSCode on neuron notes :-)

**Comment by artempyanykh** [comment]
@srid cool! Will see, maybe I'll find time soon to support both types of links.
