### ISSUE TITLE
link completion gives LSP error

### ISSUE THREAD

**Issue by kimusan** [artempyanykh/zeta-note#9]
I have tried getting this to work and I think I am almost succeeded. Unfortunately when I try to auto complete a link to another file, then I get the following error:

![image](https://user-images.githubusercontent.com/1150049/149764373-3ab38862-4b2c-491d-9e69-555fbc087bb8.png)

After this point nothing works.  I use the linux binary from the latest release and use it from within neovim. 

The actual link is shown in the autocomplete box as it is expected to. I select it and press enter.

**Comment by kimusan** [comment]
ok looks like this might be related to this one : https://github.com/hrsh7th/nvim-cmp/issues/726

**Comment by artempyanykh** [comment]
Thanks for reporting @kimusan! Yeah, UTF-8 offsets are not part of the official LSP spec; so this looks like a bug in neovim.
As Rust's strings are UTF-8 I like the idea of using it instead of calculating UTF-16 offsets; although I'd need to understand the current state of support better before trying to hack it into zeta-note.
Rebranding as a feature request #10
